In [1]:
import os
import pandas as pd
import re

raw_data_path = "data/raw"
mapping_data_path = "mappings"
output_path = "output"

PROVIDERS = [
    "Provider_A.xlsx",
    "Provider_B.xlsx",
    "Provider_C.xlsx",
    "Provider_D.xlsx",
    "Provider_E.xlsx",
]

def read_sheets(file_path):
    try:
        sheets = pd.read_excel(file_path , sheet_name=None)
        df_list = []

        for sheet_name, df in sheets.items():
            if not df.empty:
                df_list.append(df)
        return pd.concat(df_list, ignore_index=True)
    except Exception as e:
        print(f"Error {file_path} : {e}")
        return pd.DataFrame()

In [4]:
file_path = raw_data_path
sheets = pd.read_excel(file_path, sheet_name=None)

PermissionError: [Errno 13] Permission denied: 'data/raw'

In [20]:
data[0]

                   Fund     Security Name       ISIN Value ($) Currency
0     Alpha Growth Fund          Reliance  ISIN00000    $44526      INR
1      Beta Equity Fund  US Treasury Bond  ISIN00001    $19486      INR
2     Alpha Growth Fund               TCS  ISIN00002    $64012      INR
3     Gamma Income Fund  US Treasury Bond  ISIN00003    $12958      USD
4      Beta Equity Fund  US Treasury Bond  ISIN00004    $63528      INR
5     Gamma Income Fund         Microsoft  ISIN00005    $88257      INR
6      Beta Equity Fund           Infosys  ISIN00006    $72255      INR
7     Alpha Growth Fund           Infosys  ISIN00007    $76995      USD
8   Delta Opportunities           Infosys  ISIN00008    $84265      INR
9     Alpha Growth Fund         Microsoft  ISIN00009    $11165      INR
10    Gamma Income Fund         Microsoft  ISIN00010    $34058      USD
11     Beta Equity Fund           Infosys  ISIN00011    $25826      USD
12  Delta Opportunities         Microsoft  ISIN00012     $7555      INR
13     Beta Equity Fund           Infosys  ISIN00013    $33893      USD
14    Gamma Income Fund  US Treasury Bond  ISIN00014    $22154      INR
15    Alpha Growth Fund         Microsoft  ISIN00015    $43550      USD
16    Alpha Growth Fund  US Treasury Bond  ISIN00016    $24799      USD
17    Alpha Growth Fund          Reliance  ISIN00017    $33766      INR
18    Gamma Income Fund           Infosys  ISIN00018    $21777      INR
19    Alpha Growth Fund         Apple Inc  ISIN00019    $22343      USD
20    Alpha Growth Fund  US Treasury Bond  ISIN00020    $57526      INR
21    Alpha Growth Fund          Reliance  ISIN00021    $88574      USD
22    Alpha Growth Fund         Microsoft  ISIN00022     $7059      USD
23    Gamma Income Fund          Reliance  ISIN00023     $2471      USD
24     Beta Equity Fund          Reliance  ISIN00024    $15517      INR
25    Alpha Growth Fund               TCS  ISIN00025     $9361      USD
26    Gamma Income Fund          Reliance  ISIN00026    $30343      INR
27    Alpha Growth Fund           Infosys  ISIN00027    $88657      USD
28    Alpha Growth Fund         Microsoft  ISIN00028    $78639      INR
29     Beta Equity Fund  US Treasury Bond  ISIN00029     $7147      INR
30    Alpha Growth Fund         Apple Inc  ISIN00030    $87184      INR
31  Delta Opportunities          Reliance  ISIN00031    $13765      USD
32  Delta Opportunities               TCS  ISIN00032    $51226      USD
33     Beta Equity Fund               TCS  ISIN00033    $25232      INR
34  Delta Opportunities               TCS  ISIN00034    $84307      USD
35  Delta Opportunities         Microsoft  ISIN00035    $42751      INR
36    Alpha Growth Fund  US Treasury Bond  ISIN00036    $92789      USD
37    Alpha Growth Fund         Apple Inc  ISIN00037    $75597      USD
38  Delta Opportunities  US Treasury Bond  ISIN00038    $21483      INR
39  Delta Opportunities         Microsoft  ISIN00039    $35174      INR
40    Alpha Growth Fund           Infosys  ISIN00040    $49793      USD
41    Alpha Growth Fund         Apple Inc  ISIN00041    $82477      INR
42    Gamma Income Fund           Infosys  ISIN00042    $23946      USD
43    Gamma Income Fund         Microsoft  ISIN00043    $71455      INR
44     Beta Equity Fund           Infosys  ISIN00044    $69188      INR
45     Beta Equity Fund  US Treasury Bond  ISIN00045    $89109      INR
46    Alpha Growth Fund  US Treasury Bond  ISIN00046    $85601      USD
47  Delta Opportunities           Infosys  ISIN00047    $98050      INR
48    Alpha Growth Fund           Infosys  ISIN00048    $95141      INR
49    Gamma Income Fund               TCS  ISIN00049    $46749      INR

In [21]:
data[1]

                   Fund     Security Name       ISIN Value ($) Currency
0     Gamma Income Fund           Infosys  ISIN00000    $43079      USD
1   Delta Opportunities           Infosys  ISIN00001    $10230      INR
2     Alpha Growth Fund         Microsoft  ISIN00002    $37643      INR
3     Gamma Income Fund           Infosys  ISIN00003    $11501      INR
4     Alpha Growth Fund           Infosys  ISIN00004    $58501      INR
5     Alpha Growth Fund         Apple Inc  ISIN00005    $56522      INR
6     Alpha Growth Fund         Microsoft  ISIN00006    $69348      INR
7      Beta Equity Fund               TCS  ISIN00007    $67105      INR
8     Alpha Growth Fund          Reliance  ISIN00008    $68442      USD
9     Gamma Income Fund           Infosys  ISIN00009     $4494      USD
10  Delta Opportunities               TCS  ISIN00010    $69868      INR
11  Delta Opportunities         Apple Inc  ISIN00011    $70302      INR
12  Delta Opportunities          Reliance  ISIN00012    $19257      INR
13  Delta Opportunities           Infosys  ISIN00013    $86201      INR
14    Gamma Income Fund         Microsoft  ISIN00014    $60876      INR
15  Delta Opportunities  US Treasury Bond  ISIN00015    $57041      INR
16  Delta Opportunities               TCS  ISIN00016    $61249      USD
17    Alpha Growth Fund           Infosys  ISIN00017    $24061      INR
18  Delta Opportunities          Reliance  ISIN00018    $97217      INR
19    Alpha Growth Fund         Microsoft  ISIN00019    $91317      INR
20    Alpha Growth Fund          Reliance  ISIN00020    $64331      INR
21     Beta Equity Fund         Apple Inc  ISIN00021    $36112      INR
22  Delta Opportunities         Microsoft  ISIN00022    $27822      USD
23    Alpha Growth Fund               TCS  ISIN00023    $65395      INR
24    Alpha Growth Fund         Apple Inc  ISIN00024    $66176      USD
25     Beta Equity Fund         Apple Inc  ISIN00025    $38260      INR
26     Beta Equity Fund         Microsoft  ISIN00026    $86636      INR
27     Beta Equity Fund          Reliance  ISIN00027    $85843      INR
28  Delta Opportunities          Reliance  ISIN00028    $75841      INR
29  Delta Opportunities         Apple Inc  ISIN00029    $64078      USD
30     Beta Equity Fund          Reliance  ISIN00030    $46080      INR
31    Gamma Income Fund  US Treasury Bond  ISIN00031    $50930      USD
32    Alpha Growth Fund          Reliance  ISIN00032    $81412      INR
33     Beta Equity Fund         Apple Inc  ISIN00033    $34231      INR
34    Alpha Growth Fund         Microsoft  ISIN00034    $74704      USD
35     Beta Equity Fund         Microsoft  ISIN00035    $17403      INR
36     Beta Equity Fund           Infosys  ISIN00036    $38416      INR
37  Delta Opportunities          Reliance  ISIN00037    $55593      INR
38    Gamma Income Fund         Apple Inc  ISIN00038    $14532      INR
39    Alpha Growth Fund          Reliance  ISIN00039    $67507      INR
40     Beta Equity Fund  US Treasury Bond  ISIN00040    $60382      USD
41  Delta Opportunities  US Treasury Bond  ISIN00041    $66473      USD
42    Gamma Income Fund         Apple Inc  ISIN00042    $67884      USD
43     Beta Equity Fund         Apple Inc  ISIN00043     $8319      USD
44  Delta Opportunities         Microsoft  ISIN00044    $38182      USD
45    Alpha Growth Fund         Microsoft  ISIN00045    $83066      USD
46    Gamma Income Fund          Reliance  ISIN00046    $46531      INR
47  Delta Opportunities  US Treasury Bond  ISIN00047    $69079      INR
48  Delta Opportunities         Apple Inc  ISIN00048    $75989      USD
49  Delta Opportunities          Reliance  ISIN00049    $71304      USD

In [22]:
data[2]

                   Fund     Security Name       ISIN Value ($) Currency
0      Beta Equity Fund               TCS  ISIN00000    $66011      INR
1      Beta Equity Fund               TCS  ISIN00001    $48926      INR
2     Alpha Growth Fund         Apple Inc  ISIN00002    $24511      INR
3     Alpha Growth Fund         Apple Inc  ISIN00003    $27214      INR
4     Gamma Income Fund         Microsoft  ISIN00004    $99719      INR
5   Delta Opportunities         Apple Inc  ISIN00005    $60414      INR
6     Alpha Growth Fund         Apple Inc  ISIN00006    $47713      INR
7   Delta Opportunities         Microsoft  ISIN00007    $38105      INR
8     Alpha Growth Fund               TCS  ISIN00008    $39342      USD
9     Alpha Growth Fund         Microsoft  ISIN00009    $72181      USD
10  Delta Opportunities  US Treasury Bond  ISIN00010    $89199      USD
11  Delta Opportunities         Apple Inc  ISIN00011    $86606      USD
12  Delta Opportunities           Infosys  ISIN00012    $52373      INR
13    Alpha Growth Fund          Reliance  ISIN00013    $79985      INR
14    Gamma Income Fund           Infosys  ISIN00014    $95900      INR
15     Beta Equity Fund         Microsoft  ISIN00015    $60058      INR
16    Gamma Income Fund          Reliance  ISIN00016    $99252      INR
17    Alpha Growth Fund         Apple Inc  ISIN00017    $82003      INR
18  Delta Opportunities         Apple Inc  ISIN00018    $29184      INR
19  Delta Opportunities          Reliance  ISIN00019    $22829      USD
20     Beta Equity Fund          Reliance  ISIN00020     $6327      INR
21     Beta Equity Fund         Microsoft  ISIN00021    $57591      INR
22  Delta Opportunities           Infosys  ISIN00022    $98921      USD
23  Delta Opportunities          Reliance  ISIN00023    $41602      USD
24    Alpha Growth Fund  US Treasury Bond  ISIN00024    $69634      INR
25     Beta Equity Fund           Infosys  ISIN00025    $74298      INR
26    Alpha Growth Fund               TCS  ISIN00026    $94232      INR
27     Beta Equity Fund           Infosys  ISIN00027    $35627      INR
28  Delta Opportunities               TCS  ISIN00028     $9051      INR
29     Beta Equity Fund  US Treasury Bond  ISIN00029    $26630      USD

In [23]:
data[3]

                   Fund     Security Name       ISIN Value ($) Currency
0   Delta Opportunities               TCS  ISIN00000    $89315      USD
1     Gamma Income Fund          Reliance  ISIN00001    $43253      USD
2   Delta Opportunities  US Treasury Bond  ISIN00002     $7663      USD
3   Delta Opportunities           Infosys  ISIN00003    $32402      USD
4     Gamma Income Fund         Apple Inc  ISIN00004    $67913      INR
5   Delta Opportunities         Microsoft  ISIN00005     $8807      USD
6      Beta Equity Fund  US Treasury Bond  ISIN00006    $61016      INR
7     Gamma Income Fund  US Treasury Bond  ISIN00007    $23120      USD
8     Alpha Growth Fund               TCS  ISIN00008    $71081      INR
9     Gamma Income Fund           Infosys  ISIN00009    $41801      USD
10    Gamma Income Fund          Reliance  ISIN00010    $60304      USD
11    Gamma Income Fund         Apple Inc  ISIN00011    $18412      USD
12  Delta Opportunities  US Treasury Bond  ISIN00012    $40563      INR
13  Delta Opportunities         Microsoft  ISIN00013    $71109      USD
14     Beta Equity Fund               TCS  ISIN00014    $79713      USD
15  Delta Opportunities               TCS  ISIN00015    $19893      USD
16     Beta Equity Fund         Apple Inc  ISIN00016    $13722      INR
17    Alpha Growth Fund         Apple Inc  ISIN00017    $65320      INR
18    Alpha Growth Fund  US Treasury Bond  ISIN00018    $25579      INR
19    Alpha Growth Fund  US Treasury Bond  ISIN00019    $82277      USD
20    Alpha Growth Fund           Infosys  ISIN00020    $46807      INR
21     Beta Equity Fund  US Treasury Bond  ISIN00021    $72900      INR
22    Gamma Income Fund  US Treasury Bond  ISIN00022    $23669      INR
23     Beta Equity Fund               TCS  ISIN00023    $73851      USD
24  Delta Opportunities           Infosys  ISIN00024    $36114      USD
25     Beta Equity Fund               TCS  ISIN00025    $13816      USD
26    Gamma Income Fund           Infosys  ISIN00026    $67434      INR
27  Delta Opportunities         Microsoft  ISIN00027    $23255      USD
28    Gamma Income Fund               TCS  ISIN00028    $10270      INR
29  Delta Opportunities  US Treasury Bond  ISIN00029     $8259      USD
30    Alpha Growth Fund         Apple Inc  ISIN00030    $54316      INR
31     Beta Equity Fund         Microsoft  ISIN00031    $30840      INR
32    Gamma Income Fund         Apple Inc  ISIN00032    $96552      USD
33    Gamma Income Fund  US Treasury Bond  ISIN00033    $51201      USD
34     Beta Equity Fund         Microsoft  ISIN00034    $55886      USD
35  Delta Opportunities          Reliance  ISIN00035    $30729      USD
36    Gamma Income Fund  US Treasury Bond  ISIN00036    $65512      INR
37  Delta Opportunities         Microsoft  ISIN00037    $13036      INR
38    Gamma Income Fund  US Treasury Bond  ISIN00038    $49990      INR
39     Beta Equity Fund          Reliance  ISIN00039    $87897      USD
40  Delta Opportunities           Infosys  ISIN00040    $15535      INR
41  Delta Opportunities         Apple Inc  ISIN00041    $87020      USD
42    Alpha Growth Fund         Apple Inc  ISIN00042    $60093      USD
43  Delta Opportunities               TCS  ISIN00043    $80139      INR
44    Gamma Income Fund           Infosys  ISIN00044    $32611      USD
45    Gamma Income Fund               TCS  ISIN00045    $26488      USD
46  Delta Opportunities          Reliance  ISIN00046    $28733      USD
47    Gamma Income Fund         Apple Inc  ISIN00047    $63466      INR
48     Beta Equity Fund               TCS  ISIN00048    $46420      INR
49  Delta Opportunities         Apple Inc  ISIN00049    $58302      INR

In [24]:
data[4]

,Fund,Security Name,ISIN,Value ($),Currency,Quarter
0,Alpha Growth Fund,US Treasury Bond,ISIN00000,$39523,USD,2025Q1
1,Delta Opportunities,Reliance,ISIN00001,$39517,USD,2025Q1
2,Alpha Growth Fund,US Treasury Bond,ISIN00002,$44330,INR,2025Q1
3,Delta Opportunities,Reliance,ISIN00003,$28664,USD,2025Q1
4,Delta Opportunities,Apple Inc,ISIN00004,$73457,INR,2025Q1
5,Alpha Growth Fund,Apple Inc,ISIN00005,$45076,USD,2025Q1
6,Gamma Income Fund,TCS,ISIN00006,$89751,INR,2025Q1
7,Gamma Income Fund,Microsoft,ISIN00007,$87712,INR,2025Q1
8,Gamma Income Fund,Apple Inc,ISIN00008,$1197,USD,2025Q1
9,Beta Equity Fund,Microsoft,ISIN00009,$60132,USD,2025Q1
10,Beta Equity Fund,Reliance,ISIN00010,$44308,USD,2025Q1
11,Delta Opportunities,Microsoft,ISIN00011,$77707,USD,2025Q1
12,Gamma Income Fund,US Treasury Bond,ISIN00012,$50170,INR,2025Q1
13,Gamma Income Fund,TCS,ISIN00013,$60790,INR,2025Q1
14,Gamma Income Fund,US Treasury Bond,ISIN00014,$1034,INR,2025Q1
15,Beta Equity Fund,Reliance,ISIN00000,$68886,INR,2025Q2
16,Alpha Growth Fund,Apple Inc,ISIN00001,$98854,INR,2025Q2
17,Gamma Income Fund,Microsoft,ISIN00002,$88407,INR,2025Q2
18,Alpha Growth Fund,US Treasury Bond,ISIN00003,$43711,USD,2025Q2
19,Alpha Growth Fund,Apple Inc,ISIN00004,$47564,USD,2025Q2
20,Delta Opportunities,Apple Inc,ISIN00005,$61322,INR,2025Q2
21,Beta Equity Fund,TCS,ISIN00006,$51153,USD,2025Q2
22,Alpha Growth Fund,Infosys,ISIN00007,$61901,USD,2025Q2
23,Alpha Growth Fund,US Treasury Bond,ISIN00008,$35275,USD,2025Q2
24,Beta Equity Fund,Reliance,ISIN00009,$22536,INR,2025Q2
25,Beta Equity Fund,Apple Inc,ISIN00010,$80750,INR,2025Q2
26,Alpha Growth Fund,Reliance,ISIN00011,$96072,USD,2025Q2
27,Gamma Income Fund,TCS,ISIN00012,$49845,USD,2025Q2
28,Beta Equity Fund,Infosys,ISIN00013,$17426,USD,2025Q2
29,Delta Opportunities,TCS,ISIN00014,$76058,INR,2025Q2
30,Delta Opportunities,Reliance,ISIN00000,$16236,USD,2025Q3
31,Delta Opportunities,TCS,ISIN00001,$36027,USD,2025Q3
32,Gamma Income Fund,TCS,ISIN00002,$9672,INR,2025Q3
33,Alpha Growth Fund,Microsoft,ISIN00003,$28073,USD,2025Q3
34,Alpha Growth Fund,Infosys,ISIN00004,$23592,INR,2025Q3
35,Delta Opportunities,Reliance,ISIN00005,$10750,INR,2025Q3
36,Alpha Growth Fund,Reliance,ISIN00006,$42727,INR,2025Q3
37,Gamma Income Fund,US Treasury Bond,ISIN00007,$31859,USD,2025Q3
38,Beta Equity Fund,Microsoft,ISIN00008,$75759,USD,2025Q3
39,Delta Opportunities,TCS,ISIN00009,$68063,INR,2025Q3
40,Delta Opportunities,Reliance,ISIN00010,$41429,INR,2025Q3
41,Alpha Growth Fund,Microsoft,ISIN00011,$23402,INR,2025Q3
42,Alpha Growth Fund,Apple Inc,ISIN00012,$12441,USD,2025Q3
43,Beta Equity Fund,Infosys,ISIN00013,$88570,INR,2025Q3
44,Beta Equity Fund,Infosys,ISIN00014,$75430,INR,2025Q3
45,Beta Equity Fund,Infosys,ISIN00000,$86522,USD,2025Q4
46,Delta Opportunities,US Treasury Bond,ISIN00001,$97717,INR,2025Q4
47,Delta Opportunities,Microsoft,ISIN00002,$48010,USD,2025Q4
48,Gamma Income Fund,US Treasury Bond,ISIN00003,$68517,USD,2025Q4
49,Delta Opportunities,US Treasury Bond,ISIN00004,$49552,INR,2025Q4
50,Gamma Income Fund,Reliance,ISIN00005,$7076,USD,2025Q4
51,Alpha Growth Fund,Microsoft,ISIN00006,$50293,USD,2025Q4
52,Alpha Growth Fund,TCS,ISIN00007,$22677,INR,2025Q4
53,Delta Opportunities,Infosys,ISIN00008,$36445,USD,2025Q4
54,Gamma Income Fund,Microsoft,ISIN00009,$22249,USD,2025Q4
55,Gamma Income Fund,Infosys,ISIN00010,$44544,USD,2025Q4
56,Beta Equity Fund,Microsoft,ISIN00011,$87575,INR,2025Q4
57,Delta Opportunities,Infosys,ISIN00012,$54374,INR,2025Q4
58,Gamma Income Fund,TCS,ISIN00013,$8926,USD,2025Q4
59,Gamma Income Fund,Reliance,ISIN00014,$34844,INR,2025Q4

In [ ]:
for df in data:
    df.columns